-- 05_triggers.sql — 53 триггера схемы public. Требует 02 и 04.

CREATE TRIGGER update_activities_updated_at BEFORE UPDATE ON public.activities FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_application_reminders_updated_at BEFORE UPDATE ON public.application_reminders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trigger_ascetic_activities_leaderboard AFTER INSERT OR DELETE OR UPDATE ON public.ascetic_activities FOR EACH ROW EXECUTE FUNCTION trigger_update_leaderboard();
CREATE TRIGGER trigger_update_leaderboard_ascetic AFTER UPDATE ON public.ascetic_activities FOR EACH ROW EXECUTE FUNCTION update_leaderboard_on_ascetic();
CREATE TRIGGER update_leaderboard_on_ascetic AFTER INSERT OR DELETE OR UPDATE ON public.ascetic_activities FOR EACH ROW EXECUTE FUNCTION trigger_update_leaderboard();
CREATE TRIGGER update_ascetic_types_updated_at BEFORE UPDATE ON public.ascetic_types FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER validate_audit_log_entry BEFORE INSERT ON public.audit_log FOR EACH ROW EXECUTE FUNCTION validate_audit_entry();
CREATE TRIGGER validate_security_events BEFORE INSERT ON public.audit_log FOR EACH ROW EXECUTE FUNCTION validate_security_event_type();
CREATE TRIGGER update_coin_rules_updated_at BEFORE UPDATE ON public.coin_rules FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER cleanup_old_contact_submissions AFTER INSERT ON public.contact_submissions FOR EACH STATEMENT EXECUTE FUNCTION auto_delete_old_contact_submissions();
CREATE TRIGGER update_content_blocks_updated_at BEFORE UPDATE ON public.content_blocks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_contract_data_updated_at BEFORE UPDATE ON public.contract_data FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_contracts_updated_at BEFORE UPDATE ON public.contracts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trigger_crash_tests_leaderboard AFTER INSERT OR DELETE OR UPDATE ON public.crash_tests FOR EACH ROW EXECUTE FUNCTION trigger_update_leaderboard();
CREATE TRIGGER update_leaderboard_on_crash_test AFTER INSERT OR DELETE OR UPDATE ON public.crash_tests FOR EACH ROW EXECUTE FUNCTION trigger_update_leaderboard();
CREATE TRIGGER update_habit_progress_trigger AFTER INSERT OR DELETE OR UPDATE ON public.habit_progress FOR EACH ROW EXECUTE FUNCTION update_habit_completed_days();
CREATE TRIGGER trigger_hero_races_leaderboard AFTER INSERT OR DELETE OR UPDATE ON public.hero_races FOR EACH ROW EXECUTE FUNCTION trigger_update_leaderboard();
CREATE TRIGGER update_leaderboard_on_hero_race AFTER INSERT OR DELETE OR UPDATE ON public.hero_races FOR EACH ROW EXECUTE FUNCTION trigger_update_leaderboard();
CREATE TRIGGER update_hw_assignments_updated_at BEFORE UPDATE ON public.homework_assignments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trigger_homework_submissions_leaderboard AFTER INSERT OR DELETE OR UPDATE ON public.homework_submissions FOR EACH ROW EXECUTE FUNCTION trigger_update_leaderboard();
CREATE TRIGGER update_leaderboard_on_homework AFTER INSERT OR DELETE OR UPDATE ON public.homework_submissions FOR EACH ROW EXECUTE FUNCTION trigger_update_leaderboard();
CREATE TRIGGER update_journal_answers_updated_at BEFORE UPDATE ON public.journal_answers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_journal_entries_updated_at BEFORE UPDATE ON public.journal_entries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_journal_prompts_updated_at BEFORE UPDATE ON public.journal_prompts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_leaderboard_sync_public AFTER INSERT OR DELETE OR UPDATE ON public.leaderboard FOR EACH ROW EXECUTE FUNCTION sync_public_profiles_from_leaderboard();
CREATE TRIGGER trigger_lectures_leaderboard AFTER INSERT OR DELETE OR UPDATE ON public.lectures FOR EACH ROW EXECUTE FUNCTION trigger_update_leaderboard();
CREATE TRIGGER update_leaderboard_on_lecture AFTER INSERT OR DELETE OR UPDATE ON public.lectures FOR EACH ROW EXECUTE FUNCTION trigger_update_leaderboard();
CREATE TRIGGER update_materials_updated_at BEFORE UPDATE ON public.materials FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_moments_updated_at BEFORE UPDATE ON public.moments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_participant_habits_updated_at BEFORE UPDATE ON public.participant_habits FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER auto_referral_code BEFORE INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION generate_referral_code();
CREATE TRIGGER on_profile_visibility_change AFTER UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION trigger_recalculate_ranks();
CREATE TRIGGER trg_participant_status_history AFTER UPDATE OF participant_status ON public.profiles FOR EACH ROW EXECUTE FUNCTION log_participant_status_change();
CREATE TRIGGER trg_profiles_sync_public AFTER INSERT OR DELETE OR UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION sync_public_profiles();
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_public_profiles_updated_at BEFORE UPDATE ON public.public_profiles FOR EACH ROW EXECUTE FUNCTION update_timestamp_public_profiles();
CREATE TRIGGER trg_referral_settings_updated_at BEFORE UPDATE ON public.referral_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_reward_requests_updated_at BEFORE UPDATE ON public.reward_requests FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_rewards_updated_at BEFORE UPDATE ON public.rewards FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_schedules_updated_at BEFORE UPDATE ON public.schedules FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_streams_updated_at BEFORE UPDATE ON public.streams FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trigger_tactical_sessions_leaderboard AFTER INSERT OR DELETE OR UPDATE ON public.tactical_sessions FOR EACH ROW EXECUTE FUNCTION trigger_update_leaderboard();
CREATE TRIGGER update_leaderboard_on_tactical_session AFTER INSERT OR DELETE OR UPDATE ON public.tactical_sessions FOR EACH ROW EXECUTE FUNCTION trigger_update_leaderboard();
CREATE TRIGGER trg_cleanup_expired_bot_sessions AFTER INSERT ON public.telegram_bot_sessions FOR EACH STATEMENT EXECUTE FUNCTION cleanup_expired_bot_sessions();
CREATE TRIGGER update_telegram_leads_updated_at BEFORE UPDATE ON public.telegram_leads FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER auto_generate_display_name BEFORE INSERT OR UPDATE ON public.testimonials FOR EACH ROW EXECUTE FUNCTION generate_display_name();
CREATE TRIGGER set_testimonial_display_name BEFORE INSERT OR UPDATE ON public.testimonials FOR EACH ROW EXECUTE FUNCTION sync_testimonial_display_name();
CREATE TRIGGER sync_testimonials_to_public AFTER INSERT OR DELETE OR UPDATE ON public.testimonials FOR EACH ROW EXECUTE FUNCTION sync_to_public_testimonials();
CREATE TRIGGER update_testimonials_updated_at BEFORE UPDATE ON public.testimonials FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_trainers_updated_at BEFORE UPDATE ON public.trainers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trigger_training_sessions_leaderboard AFTER INSERT OR DELETE OR UPDATE ON public.training_sessions FOR EACH ROW EXECUTE FUNCTION trigger_update_leaderboard();
CREATE TRIGGER update_leaderboard_on_training_session AFTER INSERT OR DELETE OR UPDATE ON public.training_sessions FOR EACH ROW EXECUTE FUNCTION trigger_update_leaderboard();
CREATE TRIGGER role_changes_audit_trigger AFTER INSERT OR DELETE ON public.user_roles FOR EACH ROW EXECUTE FUNCTION log_role_changes();
