project_id = "wfjvjvbjjxcgkaolkgdq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.zapier-webhook]
verify_jwt = false

[functions.nodul-webhook]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.setup-super-admin]
verify_jwt = false

[functions.enhanced-security-webhook]
verify_jwt = false

[functions.calendar-feed]
verify_jwt = false

[functions.podpislon-send]
verify_jwt = false

[functions.podpislon-webhook]
verify_jwt = false
