-- 03_indexes.sql — неуникальные и частичные индексы (63). PK/UNIQUE созданы в 02.

CREATE INDEX idx_activity_checkins_user_id ON public.activity_checkins USING btree (user_id);
CREATE INDEX idx_application_notes_submission ON public.application_notes USING btree (submission_id, created_at DESC);
CREATE INDEX idx_application_reminders_pending ON public.application_reminders USING btree (remind_at) WHERE ((sent = false) AND (done = false));
CREATE INDEX idx_broadcast_responses_broadcast ON public.broadcast_responses USING btree (broadcast_id);
CREATE INDEX idx_broadcast_responses_user ON public.broadcast_responses USING btree (user_id);
CREATE INDEX idx_broadcasts_created_at ON public.broadcasts USING btree (created_at DESC);
CREATE INDEX idx_challenge_entries_user ON public.challenge_entries USING btree (challenge_id, user_id);
CREATE INDEX idx_coin_tx_source ON public.coin_transactions USING btree (source_type, source_id);
CREATE INDEX idx_coin_tx_user ON public.coin_transactions USING btree (user_id);
CREATE UNIQUE INDEX uniq_coin_tx_source_rule ON public.coin_transactions USING btree (user_id, source_type, source_id, rule_id) WHERE ((source_type IS NOT NULL) AND (source_id IS NOT NULL) AND (rule_id IS NOT NULL));
CREATE UNIQUE INDEX uq_coin_tx_referral_lead ON public.coin_transactions USING btree (source_id) WHERE (source_type = 'referral_lead'::text);
CREATE UNIQUE INDEX uq_coin_tx_telegram_lead ON public.coin_transactions USING btree (source_id) WHERE (source_type = 'telegram_lead'::text);
CREATE INDEX idx_contact_rate_limit_ip_window ON public.contact_rate_limit USING btree (ip_address, window_start DESC);
CREATE INDEX contact_submissions_utm_campaign_idx ON public.contact_submissions USING btree (((utm_data ->> 'utm_campaign'::text)));
CREATE INDEX contact_submissions_utm_source_idx ON public.contact_submissions USING btree (((utm_data ->> 'utm_source'::text)));
CREATE INDEX idx_contact_submissions_created ON public.contact_submissions USING btree (created_at DESC);
CREATE INDEX idx_contact_submissions_created_at ON public.contact_submissions USING btree (created_at);
CREATE INDEX idx_contact_submissions_status ON public.contact_submissions USING btree (status);
CREATE INDEX idx_contract_data_user_id ON public.contract_data USING btree (user_id);
CREATE INDEX idx_contracts_status ON public.contracts USING btree (status);
CREATE INDEX idx_contracts_stream_id ON public.contracts USING btree (stream_id);
CREATE INDEX idx_contracts_user_id ON public.contracts USING btree (user_id);
CREATE INDEX idx_cooper_test_user_phase ON public.cooper_test_results USING btree (user_id, test_phase);
CREATE INDEX idx_hw_assignments_active ON public.homework_assignments USING btree (is_active);
CREATE INDEX idx_hw_assignments_stream ON public.homework_assignments USING btree (stream_id) WHERE (stream_id IS NOT NULL);
CREATE INDEX idx_hw_assignments_user ON public.homework_assignments USING btree (target_user_id) WHERE (target_user_id IS NOT NULL);
CREATE INDEX idx_hw_submissions_assignment ON public.homework_submissions USING btree (assignment_id);
CREATE INDEX idx_hw_submissions_status ON public.homework_submissions USING btree (status);
CREATE INDEX idx_journal_entries_user_date ON public.journal_entries USING btree (user_id, entry_date DESC);
CREATE INDEX idx_mm_entries_member ON public.mastermind_entries USING btree (member_id);
CREATE INDEX idx_mm_members_user ON public.mastermind_members USING btree (user_id);
CREATE INDEX idx_mm_tasks_member ON public.mastermind_tasks USING btree (member_id);
CREATE INDEX idx_materials_active ON public.materials USING btree (is_active);
CREATE INDEX idx_materials_stream ON public.materials USING btree (stream_id);
CREATE INDEX idx_participant_notes_profile ON public.participant_notes USING btree (profile_user_id, created_at DESC);
CREATE INDEX idx_status_history_profile ON public.participant_status_history USING btree (profile_user_id, changed_at DESC);
CREATE INDEX idx_profile_tags_tag ON public.profile_tags USING btree (tag_id);
CREATE INDEX idx_profiles_current_stream ON public.profiles USING btree (current_stream_id);
CREATE INDEX idx_profiles_participant_status ON public.profiles USING btree (participant_status);
CREATE INDEX idx_profiles_referral_code ON public.profiles USING btree (referral_code);
CREATE UNIQUE INDEX profiles_telegram_id_unique ON public.profiles USING btree (telegram_id) WHERE (telegram_id IS NOT NULL);
CREATE UNIQUE INDEX profiles_telegram_link_code_unique ON public.profiles USING btree (telegram_link_code) WHERE (telegram_link_code IS NOT NULL);
CREATE UNIQUE INDEX public_profiles_user_id_uk ON public.public_profiles USING btree (user_id);
CREATE INDEX idx_referral_leads_code ON public.referral_leads USING btree (referral_code);
CREATE INDEX idx_referral_leads_referrer ON public.referral_leads USING btree (referrer_user_id);
CREATE INDEX idx_referral_leads_status ON public.referral_leads USING btree (status);
CREATE INDEX idx_reward_requests_status ON public.reward_requests USING btree (status);
CREATE INDEX idx_reward_requests_user ON public.reward_requests USING btree (user_id);
CREATE UNIQUE INDEX uq_schedule_participants_user ON public.schedule_participants USING btree (schedule_id, user_id);
CREATE INDEX idx_schedules_stream_id ON public.schedules USING btree (stream_id);
CREATE INDEX idx_schedules_type ON public.schedules USING btree (schedule_type);
CREATE INDEX idx_telegram_bot_logs_created_at ON public.telegram_bot_logs USING btree (created_at DESC);
CREATE INDEX idx_telegram_bot_logs_event_type ON public.telegram_bot_logs USING btree (event_type);
CREATE INDEX idx_telegram_bot_logs_telegram_id ON public.telegram_bot_logs USING btree (telegram_id);
CREATE INDEX idx_bot_sessions_expires_at ON public.telegram_bot_sessions USING btree (expires_at);
CREATE INDEX idx_bot_sessions_telegram_id ON public.telegram_bot_sessions USING btree (telegram_id);
CREATE UNIQUE INDEX telegram_leads_active_tg_uniq ON public.telegram_leads USING btree (telegram_id) WHERE (status = ANY (ARRAY['new'::text, 'waiting_admin_approval'::text]));
CREATE INDEX telegram_leads_normalized_phone_idx ON public.telegram_leads USING btree (normalized_phone);
CREATE INDEX telegram_leads_status_idx ON public.telegram_leads USING btree (status);
CREATE INDEX idx_user_totems_totem_id ON public.user_totems USING btree (totem_id);
CREATE INDEX idx_user_totems_user_id ON public.user_totems USING btree (user_id);
CREATE INDEX weekly_summaries_status_idx ON public.weekly_summaries USING btree (status);
CREATE INDEX weekly_summaries_user_id_idx ON public.weekly_summaries USING btree (user_id);
