-- 07_grants.sql — привилегии PostgREST-ролей (anon, authenticated, service_role).
-- 239 табличных GRANT + 268 GRANT EXECUTE. Доступ реально ограничивается RLS (08).

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.achievement_types TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.achievement_types TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.achievement_types TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.achievements TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.achievements TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.achievements TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.activities TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.activities TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.activities TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.activity_checkins TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.activity_checkins TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.activity_checkins TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.admin_access_log TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.admin_access_log TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.admin_access_log TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.admin_sessions TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.admin_sessions TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.admin_sessions TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.application_notes TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.application_notes TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.application_notes TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.application_reminders TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.application_reminders TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.application_reminders TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ascetic_activities TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ascetic_activities TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ascetic_activities TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ascetic_types TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ascetic_types TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ascetic_types TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.audit_log TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.audit_log TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.audit_log TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broadcast_messages TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broadcast_messages TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broadcast_messages TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broadcast_responses TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broadcast_responses TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broadcast_responses TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broadcasts TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broadcasts TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broadcasts TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.challenge_entries TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.challenge_entries TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.challenges TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.challenges TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.challenges TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.coin_rules TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.coin_rules TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.coin_rules TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.coin_transactions TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.coin_transactions TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.coin_transactions TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.contact_rate_limit TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.contact_rate_limit TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.contact_rate_limit TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.contact_submissions TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.contact_submissions TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.contact_submissions TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.content_blocks TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.content_blocks TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.content_blocks TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.contract_data TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.contract_data TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.contract_data TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.contracts TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.contracts TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.contracts TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.cooper_test_results TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.cooper_test_results TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.cooper_test_results TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.crash_tests TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.crash_tests TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.crash_tests TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.habit_progress TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.habit_progress TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.habit_progress TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.hero_races TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.hero_races TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.hero_races TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.homework_assignments TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.homework_assignments TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.homework_assignments TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.homework_submissions TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.homework_submissions TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.homework_submissions TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.intensive_streams TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.intensive_streams TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.intensive_streams TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.journal_answers TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.journal_answers TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.journal_answers TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.journal_emotions TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.journal_emotions TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.journal_emotions TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.journal_entries TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.journal_entries TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.journal_entries TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.journal_prompts TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.journal_prompts TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.journal_prompts TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.leaderboard TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.leaderboard TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.leaderboard TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.lectures TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.lectures TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.lectures TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.mastermind_entries TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.mastermind_entries TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.mastermind_entries TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.mastermind_groups TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.mastermind_groups TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.mastermind_groups TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.mastermind_members TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.mastermind_members TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.mastermind_members TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.mastermind_tasks TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.mastermind_tasks TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.mastermind_tasks TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.materials TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.materials TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.materials TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.moments TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.moments TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.moments TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.notifications TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.notifications TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.notifications TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.participant_habits TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.participant_habits TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.participant_habits TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.participant_notes TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.participant_notes TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.participant_notes TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.participant_status_history TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.participant_status_history TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.participant_status_history TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.participant_tags TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.participant_tags TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.participant_tags TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.profile_tags TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.profile_tags TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.profile_tags TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.profiles TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.profiles TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.profiles TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.public_profiles TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.public_profiles TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.public_profiles TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.public_testimonials TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.public_testimonials TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.public_testimonials TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.pyramid_levels TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.pyramid_levels TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.pyramid_levels TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.referral_leads TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.referral_leads TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.referral_leads TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.referral_settings TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.referral_settings TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.referral_settings TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.reward_requests TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.reward_requests TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.reward_requests TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.rewards TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.rewards TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.rewards TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.role_audit_log TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.role_audit_log TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.role_audit_log TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.schedule_participants TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.schedule_participants TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.schedule_participants TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.schedules TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.schedules TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.schedules TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.streams TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.streams TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.streams TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.tactical_sessions TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.tactical_sessions TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.tactical_sessions TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.telegram_bot_logs TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.telegram_bot_logs TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.telegram_bot_logs TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.telegram_bot_sessions TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.telegram_bot_sessions TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.telegram_bot_sessions TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.telegram_leads TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.telegram_leads TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.telegram_leads TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.testimonials TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.testimonials TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.testimonials TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.totems TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.totems TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.totems TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.trainers TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.trainers TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.trainers TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.training_programs TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.training_programs TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.training_programs TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.training_sessions TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.training_sessions TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.training_sessions TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_achievements TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_achievements TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_achievements TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_activities TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_activities TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_activities TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_challenges TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_challenges TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_challenges TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_points TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_points TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_points TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_roles TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_roles TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_roles TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_totems TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_totems TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_totems TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.weekly_summaries TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.weekly_summaries TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.weekly_summaries TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public."аскезы_участников" TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public."аскезы_участников" TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public."аскезы_участников" TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public."кэмп_активности" TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public."кэмп_активности" TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public."кэмп_активности" TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public."тотемы_участников" TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public."тотемы_участников" TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public."тотемы_участников" TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public."участники" TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public."участники" TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public."участники" TO service_role;

-- function grants
GRANT EXECUTE ON FUNCTION public.admin_adjust_coins(p_user_id uuid, p_amount integer, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_adjust_coins(p_user_id uuid, p_amount integer, p_reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_adjust_coins(p_user_id uuid, p_amount integer, p_reason text) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_confirm_referral(p_lead_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_confirm_referral(p_lead_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_confirm_referral(p_lead_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_list_coin_balances() TO anon;
GRANT EXECUTE ON FUNCTION public.admin_list_coin_balances() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_coin_balances() TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_set_approval(p_user_id uuid, p_approved boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_set_approval(p_user_id uuid, p_approved boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_approval(p_user_id uuid, p_approved boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.auto_cleanup_contact_submissions() TO anon;
GRANT EXECUTE ON FUNCTION public.auto_cleanup_contact_submissions() TO authenticated;
GRANT EXECUTE ON FUNCTION public.auto_cleanup_contact_submissions() TO service_role;
GRANT EXECUTE ON FUNCTION public.auto_delete_old_contact_submissions() TO anon;
GRANT EXECUTE ON FUNCTION public.auto_delete_old_contact_submissions() TO authenticated;
GRANT EXECUTE ON FUNCTION public.auto_delete_old_contact_submissions() TO service_role;
GRANT EXECUTE ON FUNCTION public.award_coins_by_rule(p_user_id uuid, p_rule_code text, p_source_type text, p_source_id uuid, p_reason text, p_amount_override integer) TO anon;
GRANT EXECUTE ON FUNCTION public.award_coins_by_rule(p_user_id uuid, p_rule_code text, p_source_type text, p_source_id uuid, p_reason text, p_amount_override integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.award_coins_by_rule(p_user_id uuid, p_rule_code text, p_source_type text, p_source_id uuid, p_reason text, p_amount_override integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.book_schedule_session(p_telegram_id text, p_schedule_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.book_schedule_session(p_telegram_id text, p_schedule_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.book_schedule_session(p_telegram_id text, p_schedule_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.calculate_cooper_fitness_level(total_seconds integer) TO anon;
GRANT EXECUTE ON FUNCTION public.calculate_cooper_fitness_level(total_seconds integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_cooper_fitness_level(total_seconds integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.calculate_cooper_fitness_level_minutes(total_minutes integer) TO anon;
GRANT EXECUTE ON FUNCTION public.calculate_cooper_fitness_level_minutes(total_minutes integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_cooper_fitness_level_minutes(total_minutes integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.check_in_activity(p_telegram_id text, p_activity_type text) TO anon;
GRANT EXECUTE ON FUNCTION public.check_in_activity(p_telegram_id text, p_activity_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_in_activity(p_telegram_id text, p_activity_type text) TO service_role;
GRANT EXECUTE ON FUNCTION public.checkin_ascetic(p_telegram_id text, p_ascetic_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.checkin_ascetic(p_telegram_id text, p_ascetic_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.checkin_ascetic(p_telegram_id text, p_ascetic_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_bot_sessions() TO anon;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_bot_sessions() TO authenticated;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_bot_sessions() TO service_role;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_sessions() TO anon;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_sessions() TO authenticated;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_sessions() TO service_role;
GRANT EXECUTE ON FUNCTION public.cleanup_old_audit_logs() TO anon;
GRANT EXECUTE ON FUNCTION public.cleanup_old_audit_logs() TO authenticated;
GRANT EXECUTE ON FUNCTION public.cleanup_old_audit_logs() TO service_role;
GRANT EXECUTE ON FUNCTION public.confirm_referral_lead(_lead_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.confirm_referral_lead(_lead_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.confirm_referral_lead(_lead_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.create_reward_request(p_reward_id uuid, p_user_comment text) TO anon;
GRANT EXECUTE ON FUNCTION public.create_reward_request(p_reward_id uuid, p_user_comment text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_reward_request(p_reward_id uuid, p_user_comment text) TO service_role;
GRANT EXECUTE ON FUNCTION public.decrypt_phone(encrypted_phone text) TO anon;
GRANT EXECUTE ON FUNCTION public.decrypt_phone(encrypted_phone text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.decrypt_phone(encrypted_phone text) TO service_role;
GRANT EXECUTE ON FUNCTION public.encrypt_phone(phone_text text) TO anon;
GRANT EXECUTE ON FUNCTION public.encrypt_phone(phone_text text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.encrypt_phone(phone_text text) TO service_role;
GRANT EXECUTE ON FUNCTION public.enhanced_contact_rate_limit(p_ip_address inet) TO anon;
GRANT EXECUTE ON FUNCTION public.enhanced_contact_rate_limit(p_ip_address inet) TO authenticated;
GRANT EXECUTE ON FUNCTION public.enhanced_contact_rate_limit(p_ip_address inet) TO service_role;
GRANT EXECUTE ON FUNCTION public.enhanced_rate_limit_check(p_ip_address inet, p_action text) TO anon;
GRANT EXECUTE ON FUNCTION public.enhanced_rate_limit_check(p_ip_address inet, p_action text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.enhanced_rate_limit_check(p_ip_address inet, p_action text) TO service_role;
GRANT EXECUTE ON FUNCTION public.enroll_application(p_submission_id uuid, p_stream_id uuid, p_user_id uuid, p_new_status participant_status_type) TO anon;
GRANT EXECUTE ON FUNCTION public.enroll_application(p_submission_id uuid, p_stream_id uuid, p_user_id uuid, p_new_status participant_status_type) TO authenticated;
GRANT EXECUTE ON FUNCTION public.enroll_application(p_submission_id uuid, p_stream_id uuid, p_user_id uuid, p_new_status participant_status_type) TO service_role;
GRANT EXECUTE ON FUNCTION public.ensure_referral_code(_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.ensure_referral_code(_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ensure_referral_code(_user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_display_name() TO anon;
GRANT EXECUTE ON FUNCTION public.generate_display_name() TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_display_name() TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_referral_code() TO anon;
GRANT EXECUTE ON FUNCTION public.generate_referral_code() TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_referral_code() TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_telegram_link_code(p_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_telegram_link_code(p_user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_ascetic_for_user(p_telegram_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_ascetic_for_user(p_telegram_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_ascetic_for_user(p_telegram_id text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_broadcast_audience(filter_json jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.get_broadcast_audience(filter_json jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_broadcast_audience(filter_json jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_homework_for_user(p_telegram_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_homework_for_user(p_telegram_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_homework_for_user(p_telegram_id text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_journal_for_user(p_telegram_id text, p_date date) TO anon;
GRANT EXECUTE ON FUNCTION public.get_journal_for_user(p_telegram_id text, p_date date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_journal_for_user(p_telegram_id text, p_date date) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_participant_full_state(p_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_participant_full_state(p_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_participant_full_state(p_user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_participant_full_state_by_telegram(p_telegram_id text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_participant_timeline(_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_participant_timeline(_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_participant_timeline(_user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_profile_for_user(p_telegram_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_profile_for_user(p_telegram_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_profile_for_user(p_telegram_id text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_pyramid_for_user(p_telegram_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_pyramid_for_user(p_telegram_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_pyramid_for_user(p_telegram_id text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_rating_for_user(p_telegram_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_rating_for_user(p_telegram_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_rating_for_user(p_telegram_id text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_schedule_for_user(p_telegram_id text, p_from timestamp with time zone, p_days integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_schedule_for_user(p_telegram_id text, p_from timestamp with time zone, p_days integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_schedule_for_user(p_telegram_id text, p_from timestamp with time zone, p_days integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_user_coin_balance(p_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_user_coin_balance(p_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_coin_balance(p_user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO anon;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO authenticated;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO service_role;
GRANT EXECUTE ON FUNCTION public.handle_new_user_participant() TO anon;
GRANT EXECUTE ON FUNCTION public.handle_new_user_participant() TO authenticated;
GRANT EXECUTE ON FUNCTION public.handle_new_user_participant() TO service_role;
GRANT EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role user_role) TO anon;
GRANT EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role user_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role user_role) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_admin(_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_admin(_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin(_user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_club_resident(_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_club_resident(_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_club_resident(_user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_public_participant(_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_public_participant(_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_public_participant(_user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_super_admin(_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_super_admin(_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_super_admin(_user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.link_or_create_telegram_profile(p_telegram_id text, p_telegram_username text, p_telegram_first_name text, p_telegram_last_name text, p_phone text, p_referral_code text) TO service_role;
GRANT EXECUTE ON FUNCTION public.link_telegram_lead_to_profile(p_lead_id uuid, p_profile_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.link_telegram_lead_to_profile(p_lead_id uuid, p_profile_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.link_telegram_lead_to_profile(p_lead_id uuid, p_profile_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.link_telegram_profile(p_link_code text, p_telegram_id text, p_telegram_username text, p_telegram_first_name text, p_telegram_last_name text, p_telegram_photo_url text) TO service_role;
GRANT EXECUTE ON FUNCTION public.log_contact_form_access() TO anon;
GRANT EXECUTE ON FUNCTION public.log_contact_form_access() TO authenticated;
GRANT EXECUTE ON FUNCTION public.log_contact_form_access() TO service_role;
GRANT EXECUTE ON FUNCTION public.log_participant_status_change() TO anon;
GRANT EXECUTE ON FUNCTION public.log_participant_status_change() TO authenticated;
GRANT EXECUTE ON FUNCTION public.log_participant_status_change() TO service_role;
GRANT EXECUTE ON FUNCTION public.log_role_changes() TO anon;
GRANT EXECUTE ON FUNCTION public.log_role_changes() TO authenticated;
GRANT EXECUTE ON FUNCTION public.log_role_changes() TO service_role;
GRANT EXECUTE ON FUNCTION public.log_security_access(p_action text, p_table_name text, p_record_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.log_security_access(p_action text, p_table_name text, p_record_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.log_security_access(p_action text, p_table_name text, p_record_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.log_security_event(event_type text, user_id_param uuid, details jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.log_security_event(event_type text, user_id_param uuid, details jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.log_security_event(event_type text, user_id_param uuid, details jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.mask_email_secure(email_address text) TO anon;
GRANT EXECUTE ON FUNCTION public.mask_email_secure(email_address text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mask_email_secure(email_address text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mask_participant_name(full_name text) TO anon;
GRANT EXECUTE ON FUNCTION public.mask_participant_name(full_name text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mask_participant_name(full_name text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mask_phone_number(phone_number text) TO anon;
GRANT EXECUTE ON FUNCTION public.mask_phone_number(phone_number text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mask_phone_number(phone_number text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mask_phone_secure(phone_number text) TO anon;
GRANT EXECUTE ON FUNCTION public.mask_phone_secure(phone_number text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mask_phone_secure(phone_number text) TO service_role;
GRANT EXECUTE ON FUNCTION public.normalize_phone(p_phone text) TO anon;
GRANT EXECUTE ON FUNCTION public.normalize_phone(p_phone text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.normalize_phone(p_phone text) TO service_role;
GRANT EXECUTE ON FUNCTION public.recalculate_all_ranks() TO anon;
GRANT EXECUTE ON FUNCTION public.recalculate_all_ranks() TO authenticated;
GRANT EXECUTE ON FUNCTION public.recalculate_all_ranks() TO service_role;
GRANT EXECUTE ON FUNCTION public.review_homework_submission(p_submission_id uuid, p_status text, p_admin_comment text) TO anon;
GRANT EXECUTE ON FUNCTION public.review_homework_submission(p_submission_id uuid, p_status text, p_admin_comment text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.review_homework_submission(p_submission_id uuid, p_status text, p_admin_comment text) TO service_role;
GRANT EXECUTE ON FUNCTION public.review_reward_request(p_request_id uuid, p_new_status text, p_admin_comment text) TO anon;
GRANT EXECUTE ON FUNCTION public.review_reward_request(p_request_id uuid, p_new_status text, p_admin_comment text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.review_reward_request(p_request_id uuid, p_new_status text, p_admin_comment text) TO service_role;
GRANT EXECUTE ON FUNCTION public.save_journal_entry(p_telegram_id text, p_entry_date date, p_day_type text, p_emotions jsonb, p_answers jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.save_journal_entry(p_telegram_id text, p_entry_date date, p_day_type text, p_emotions jsonb, p_answers jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_journal_entry(p_telegram_id text, p_entry_date date, p_day_type text, p_emotions jsonb, p_answers jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.server_challenge_checkin(p_user_id uuid, p_challenge_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.server_challenge_checkin(p_user_id uuid, p_challenge_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.server_challenge_checkin(p_user_id uuid, p_challenge_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.server_complete_mastermind_task(p_user_id uuid, p_task_id uuid, p_comment text, p_file_url text) TO anon;
GRANT EXECUTE ON FUNCTION public.server_complete_mastermind_task(p_user_id uuid, p_task_id uuid, p_comment text, p_file_url text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.server_complete_mastermind_task(p_user_id uuid, p_task_id uuid, p_comment text, p_file_url text) TO service_role;
GRANT EXECUTE ON FUNCTION public.server_create_mastermind_task(p_user_id uuid, p_title text, p_description text, p_deadline date) TO anon;
GRANT EXECUTE ON FUNCTION public.server_create_mastermind_task(p_user_id uuid, p_title text, p_description text, p_deadline date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.server_create_mastermind_task(p_user_id uuid, p_title text, p_description text, p_deadline date) TO service_role;
GRANT EXECUTE ON FUNCTION public.server_create_reward_request(p_user_id uuid, p_reward_id uuid, p_user_comment text) TO anon;
GRANT EXECUTE ON FUNCTION public.server_create_reward_request(p_user_id uuid, p_reward_id uuid, p_user_comment text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.server_create_reward_request(p_user_id uuid, p_reward_id uuid, p_user_comment text) TO service_role;
GRANT EXECUTE ON FUNCTION public.server_register_for_event(p_user_id uuid, p_schedule_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.server_register_for_event(p_user_id uuid, p_schedule_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.server_register_for_event(p_user_id uuid, p_schedule_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.server_submit_mastermind_entry(p_user_id uuid, p_summary text, p_my_tasks text) TO anon;
GRANT EXECUTE ON FUNCTION public.server_submit_mastermind_entry(p_user_id uuid, p_summary text, p_my_tasks text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.server_submit_mastermind_entry(p_user_id uuid, p_summary text, p_my_tasks text) TO service_role;
GRANT EXECUTE ON FUNCTION public.server_unregister_from_event(p_user_id uuid, p_schedule_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.server_unregister_from_event(p_user_id uuid, p_schedule_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.server_unregister_from_event(p_user_id uuid, p_schedule_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.submit_homework(p_telegram_id text, p_assignment_id uuid, p_content text) TO anon;
GRANT EXECUTE ON FUNCTION public.submit_homework(p_telegram_id text, p_assignment_id uuid, p_content text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_homework(p_telegram_id text, p_assignment_id uuid, p_content text) TO service_role;
GRANT EXECUTE ON FUNCTION public.submit_homework(p_telegram_id text, p_assignment_id uuid, p_content text, p_file_url text) TO anon;
GRANT EXECUTE ON FUNCTION public.submit_homework(p_telegram_id text, p_assignment_id uuid, p_content text, p_file_url text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_homework(p_telegram_id text, p_assignment_id uuid, p_content text, p_file_url text) TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_public_profiles() TO anon;
GRANT EXECUTE ON FUNCTION public.sync_public_profiles() TO authenticated;
GRANT EXECUTE ON FUNCTION public.sync_public_profiles() TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_public_profiles_from_leaderboard() TO anon;
GRANT EXECUTE ON FUNCTION public.sync_public_profiles_from_leaderboard() TO authenticated;
GRANT EXECUTE ON FUNCTION public.sync_public_profiles_from_leaderboard() TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_testimonial_display_name() TO anon;
GRANT EXECUTE ON FUNCTION public.sync_testimonial_display_name() TO authenticated;
GRANT EXECUTE ON FUNCTION public.sync_testimonial_display_name() TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_to_public_testimonials() TO anon;
GRANT EXECUTE ON FUNCTION public.sync_to_public_testimonials() TO authenticated;
GRANT EXECUTE ON FUNCTION public.sync_to_public_testimonials() TO service_role;
GRANT EXECUTE ON FUNCTION public.take_ascetic(p_telegram_id text, p_text text) TO anon;
GRANT EXECUTE ON FUNCTION public.take_ascetic(p_telegram_id text, p_text text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.take_ascetic(p_telegram_id text, p_text text) TO service_role;
GRANT EXECUTE ON FUNCTION public.trigger_recalculate_ranks() TO anon;
GRANT EXECUTE ON FUNCTION public.trigger_recalculate_ranks() TO authenticated;
GRANT EXECUTE ON FUNCTION public.trigger_recalculate_ranks() TO service_role;
GRANT EXECUTE ON FUNCTION public.trigger_update_leaderboard() TO anon;
GRANT EXECUTE ON FUNCTION public.trigger_update_leaderboard() TO authenticated;
GRANT EXECUTE ON FUNCTION public.trigger_update_leaderboard() TO service_role;
GRANT EXECUTE ON FUNCTION public.unlink_telegram_profile(p_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.unlink_telegram_profile(p_user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.update_avatar_for_user(p_telegram_id text, p_avatar_url text) TO anon;
GRANT EXECUTE ON FUNCTION public.update_avatar_for_user(p_telegram_id text, p_avatar_url text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_avatar_for_user(p_telegram_id text, p_avatar_url text) TO service_role;
GRANT EXECUTE ON FUNCTION public.update_habit_completed_days() TO anon;
GRANT EXECUTE ON FUNCTION public.update_habit_completed_days() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_habit_completed_days() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_leaderboard_on_ascetic() TO anon;
GRANT EXECUTE ON FUNCTION public.update_leaderboard_on_ascetic() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_leaderboard_on_ascetic() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_participant_status(p_user_id uuid, p_new_status participant_status_type) TO anon;
GRANT EXECUTE ON FUNCTION public.update_participant_status(p_user_id uuid, p_new_status participant_status_type) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_participant_status(p_user_id uuid, p_new_status participant_status_type) TO service_role;
GRANT EXECUTE ON FUNCTION public.update_profile_for_user(p_telegram_id text, p_weight_kg integer, p_height_cm integer, p_date_of_birth date) TO anon;
GRANT EXECUTE ON FUNCTION public.update_profile_for_user(p_telegram_id text, p_weight_kg integer, p_height_cm integer, p_date_of_birth date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_profile_for_user(p_telegram_id text, p_weight_kg integer, p_height_cm integer, p_date_of_birth date) TO service_role;
GRANT EXECUTE ON FUNCTION public.update_timestamp_public_profiles() TO anon;
GRANT EXECUTE ON FUNCTION public.update_timestamp_public_profiles() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_timestamp_public_profiles() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_updated_at_column() TO anon;
GRANT EXECUTE ON FUNCTION public.update_updated_at_column() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_updated_at_column() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_user_leaderboard(user_uuid uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.update_user_leaderboard(user_uuid uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_user_leaderboard(user_uuid uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.validate_audit_entry() TO anon;
GRANT EXECUTE ON FUNCTION public.validate_audit_entry() TO authenticated;
GRANT EXECUTE ON FUNCTION public.validate_audit_entry() TO service_role;
GRANT EXECUTE ON FUNCTION public.validate_audit_log_entry(p_action text, p_table_name text, p_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.validate_audit_log_entry(p_action text, p_table_name text, p_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.validate_audit_log_entry(p_action text, p_table_name text, p_user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.validate_contact_submission(p_name text, p_phone text, p_course text, p_social text) TO anon;
GRANT EXECUTE ON FUNCTION public.validate_contact_submission(p_name text, p_phone text, p_course text, p_social text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.validate_contact_submission(p_name text, p_phone text, p_course text, p_social text) TO service_role;
GRANT EXECUTE ON FUNCTION public.validate_referral_code(p_code text) TO anon;
GRANT EXECUTE ON FUNCTION public.validate_referral_code(p_code text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.validate_referral_code(p_code text) TO service_role;
GRANT EXECUTE ON FUNCTION public.validate_security_event_type() TO anon;
GRANT EXECUTE ON FUNCTION public.validate_security_event_type() TO authenticated;
GRANT EXECUTE ON FUNCTION public.validate_security_event_type() TO service_role;
