// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/supabaseForUser.ts
import { createClient } from "npm:@supabase/supabase-js@^2.57.4";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anonKey = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY ?? "";
  return createClient(url, anonKey, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in \u041A\u042D\u041C\u041F user's profile: name, status, telegram and approval flag.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(
      "user_id, display_name, first_name, last_name, telegram, participant_type, approved"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? { found: false }) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/tools/get-my-coins.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_my_coins_default = defineTool2({
  name: "get_my_coins",
  title: "Get my coins",
  description: "Return the signed-in user's current coin balance and their most recent coin transactions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: balance, error: balanceError } = await supabase.rpc(
      "get_user_coin_balance",
      { p_user_id: userId }
    );
    if (balanceError) {
      return { content: [{ type: "text", text: balanceError.message }], isError: true };
    }
    const { data: txns, error: txnError } = await supabase.from("coin_transactions").select("amount, reason, created_at").eq("user_id", userId).order("created_at", { ascending: false }).limit(20);
    if (txnError) {
      return { content: [{ type: "text", text: txnError.message }], isError: true };
    }
    const result = { balance: balance ?? 0, transactions: txns ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-my-homework.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_my_homework_default = defineTool3({
  name: "list_my_homework",
  title: "List my homework",
  description: "Return the signed-in user's homework submissions with status, points and timestamps.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("homework_submissions").select(
      "id, homework_type, status, points_earned, verified, admin_comment, submitted_at, reviewed_at"
    ).eq("user_id", ctx.getUserId()).order("submitted_at", { ascending: false }).limit(50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { submissions: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wfjvjvbjjxcgkaolkgdq";
var mcp_default = defineMcp({
  name: "kemp-club-mcp",
  title: "\u041A\u042D\u041C\u041F Club MCP",
  version: "0.1.0",
  instructions: "Tools for the \u041A\u042D\u041C\u041F Club member area. Each caller connects as a signed-in user and can read their own profile, coin balance and homework.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, get_my_coins_default, list_my_homework_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
