import React, { useCallback, useEffect, useState } from 'react';
import { Award, Camera, FileText, Lock, ScrollText, Star, Trophy } from 'lucide-react';
import { useAppApi } from '@/components/app-shared/apiAdapter';
import { supabase } from '@/integrations/supabase/client';
import { proxyStorageUrl } from '@/lib/storageUrl';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';

const Header = ({ title, subtitle }: { title: string; subtitle?: string }) => <header className="bg-kamp-primary px-4 pb-6 pt-8 text-center"><h1 className="text-xl font-bold text-primary-foreground">{title}</h1>{subtitle && <p className="mt-1 text-sm text-primary-foreground/75">{subtitle}</p>}</header>;
const Loading = ({ text }: { text: string }) => <p className="py-12 text-center text-sm text-muted-foreground">{text}</p>;
const ErrorText = ({ text, retry }: { text: string; retry: () => void }) => <div className="space-y-3 py-12 text-center"><p className="text-sm text-destructive">{text}</p><Button size="sm" variant="outline" onClick={retry}>Повторить</Button></div>;

interface RatingData { my: { rank_position: number | null; total_points: number; breakdown: Record<string, number>; attendance: { total: number; by_type: { activity_type: string; count: number }[] } }; leaderboard: { user_id: string; display_name: string | null; first_name: string | null; last_name: string | null; avatar_url: string | null; rank_position: number | null; total_points: number; is_me: boolean }[] }
const ratingLabels: Record<string, string> = { bjj: 'BJJ', kickboxing: 'Кикбоксинг', ofp: 'ОФП', theory: 'Теория', tactical: 'Тактика', nutrition: 'Нутрициология', kamp_pyramid: 'Пирамида КЭМП', challenges: 'Челленджи' };

export const WebRatingView = () => {
  const { callApi } = useAppApi(); const [data, setData] = useState<RatingData | null>(null); const [error, setError] = useState('');
  const load = useCallback(() => { setError(''); callApi<RatingData>('get_rating').then(d => setData({ ...d, my: { rank_position: d?.my?.rank_position ?? null, total_points: d?.my?.total_points ?? 0, breakdown: d?.my?.breakdown ?? {}, attendance: d?.my?.attendance ?? { total: 0, by_type: [] } }, leaderboard: d?.leaderboard ?? [] })).catch((e: unknown) => setError(e instanceof Error ? e.message : 'Ошибка загрузки')); }, [callApi]);
  useEffect(load, [load]);
  return <div className="min-h-screen pb-24"><Header title="Рейтинг" subtitle="Твой прогресс и топ потока"/><main className="space-y-5 p-4">{error ? <ErrorText text={error} retry={load}/> : !data ? <Loading text="Загрузка рейтинга..."/> : <><div className="grid grid-cols-2 gap-3"><Card><CardContent className="p-4"><Star className="mb-2 h-5 w-5 text-kamp-primary"/><p className="text-xs text-muted-foreground">Место</p><p className="text-xl font-bold">{data.my.rank_position ? `#${data.my.rank_position}` : '—'}</p></CardContent></Card><Card><CardContent className="p-4"><Trophy className="mb-2 h-5 w-5 text-kamp-primary"/><p className="text-xs text-muted-foreground">Очки</p><p className="text-xl font-bold">{data.my.total_points}</p></CardContent></Card></div><Card><CardContent className="space-y-2 p-4"><p className="text-sm font-semibold">Детализация</p>{Object.entries(data.my.breakdown).map(([key, value]) => <div key={key} className="flex justify-between text-sm"><span className="text-muted-foreground">{ratingLabels[key] ?? key}</span><strong>{value}</strong></div>)}</CardContent></Card><section className="space-y-2"><p className="text-xs font-semibold uppercase text-muted-foreground">Топ потока</p>{data.leaderboard.map(row => { const name = row.display_name || [row.first_name,row.last_name].filter(Boolean).join(' ') || 'Участник'; return <Card key={row.user_id} className={row.is_me ? 'border-kamp-primary' : ''}><CardContent className="flex items-center gap-3 p-3"><span className="w-7 font-bold">#{row.rank_position ?? '—'}</span><div className="h-9 w-9 overflow-hidden rounded-full bg-primary/10">{row.avatar_url ? <img src={proxyStorageUrl(row.avatar_url)} alt={name} className="h-full w-full object-cover"/> : <span className="flex h-full items-center justify-center text-sm font-bold">{name[0]}</span>}</div><span className="min-w-0 flex-1 truncate text-sm">{name}{row.is_me ? ' (ты)' : ''}</span><strong>{row.total_points}</strong></CardContent></Card>})}</section></>}</main></div>;
};

interface ProfileData { profile: { first_name: string | null; last_name: string | null; avatar_url: string | null; weight_kg: number | null; height_cm: number | null; date_of_birth: string | null }; cooper_test: { test_date: string; total_minutes: number | null; total_seconds: number | null; fitness_level: string | null } | null; totems: { id: string; name: string; discipline: string }[] }
export const WebProfileView = () => {
  const { callApi } = useAppApi(); const [data,setData]=useState<ProfileData|null>(null); const [error,setError]=useState(''); const [weight,setWeight]=useState(''); const [height,setHeight]=useState(''); const [birth,setBirth]=useState(''); const [busy,setBusy]=useState(false);
  const load=useCallback(()=>{setError('');callApi<ProfileData>('get_profile').then(d=>{setData(d);setWeight(d.profile.weight_kg?.toString()??'');setHeight(d.profile.height_cm?.toString()??'');setBirth(d.profile.date_of_birth??'');}).catch((e:unknown)=>setError(e instanceof Error?e.message:'Ошибка загрузки'));},[callApi]); useEffect(load,[load]);
  const upload=async(file:File)=>{setBusy(true);setError('');try{const {data:user}=await supabase.auth.getUser();if(!user.user)throw new Error('Нет авторизации');const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${user.user.id}/avatar-${Date.now()}.${ext}`;const {error:up}=await supabase.storage.from('avatars').upload(path,file,{upsert:true});if(up)throw up;const url=supabase.storage.from('avatars').getPublicUrl(path).data.publicUrl;await callApi('update_avatar',{avatar_url:url});await load();}catch(e){setError(e instanceof Error?e.message:'Ошибка загрузки фото');}finally{setBusy(false)}};
  const save=async()=>{setBusy(true);setError('');try{await callApi('update_profile',{weight:weight?Number(weight):null,height:height?Number(height):null,birth_date:birth||null});await load();}catch(e){setError(e instanceof Error?e.message:'Ошибка сохранения');}finally{setBusy(false)}};
  const name=data?[data.profile.first_name,data.profile.last_name].filter(Boolean).join(' ')||'Участник':'';
  return <div className="min-h-screen pb-24"><Header title="Профиль"/><main className="space-y-4 p-4">{error&&<p className="text-center text-sm text-destructive">{error}</p>}{!data?<Loading text="Загрузка профиля..."/>:<><Card><CardContent className="space-y-4 p-4"><div className="flex flex-col items-center gap-2"><div className="h-20 w-20 overflow-hidden rounded-md bg-primary/10">{data.profile.avatar_url?<img src={proxyStorageUrl(data.profile.avatar_url)} alt={name} className="h-full w-full object-cover"/>:<span className="flex h-full items-center justify-center text-2xl font-bold">{name[0]}</span>}</div><label className="flex cursor-pointer items-center gap-1 text-xs text-kamp-primary"><Camera className="h-4 w-4"/>{busy?'Загрузка...':'Загрузить фото'}<input type="file" accept="image/*" className="hidden" disabled={busy} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f&&f.size<=5*1024*1024)void upload(f);}}/></label><strong>{name}</strong></div><div className="grid grid-cols-2 gap-3"><Input aria-label="Вес" type="number" placeholder="Вес, кг" value={weight} onChange={e=>setWeight(e.target.value)}/><Input aria-label="Рост" type="number" placeholder="Рост, см" value={height} onChange={e=>setHeight(e.target.value)}/></div><Input aria-label="Дата рождения" type="date" value={birth} onChange={e=>setBirth(e.target.value)}/><Button className="w-full" disabled={busy} onClick={()=>void save()}>{busy?'Сохраняем...':'Сохранить'}</Button></CardContent></Card><Card><CardContent className="p-4"><p className="mb-2 text-sm font-semibold">Тест Купера</p>{data.cooper_test?<p className="text-sm text-muted-foreground">{data.cooper_test.total_minutes??0} мин {String(data.cooper_test.total_seconds??0).padStart(2,'0')} сек · {new Date(data.cooper_test.test_date).toLocaleDateString('ru-RU')}</p>:<p className="text-sm text-muted-foreground">Пока нет результатов</p>}</CardContent></Card><Card><CardContent className="space-y-2 p-4"><p className="text-sm font-semibold">Тотемы</p>{data.totems.length?data.totems.map(t=><div key={t.id} className="flex gap-2 text-sm"><Award className="h-4 w-4 text-kamp-primary"/><span>{t.name} · <span className="text-muted-foreground">{t.discipline}</span></span></div>):<p className="text-sm text-muted-foreground">Пока нет тотемов</p>}</CardContent></Card></>}</main></div>;
};

interface RulesData { documents: { doc_type: string; title: string; content: string | null; file_url: string | null }[] }
export const WebRulesView = () => { const {callApi}=useAppApi();const [data,setData]=useState<RulesData|null>(null);const [error,setError]=useState('');const load=useCallback(()=>{setError('');callApi<RulesData>('get_rules').then(setData).catch((e:unknown)=>setError(e instanceof Error?e.message:'Ошибка загрузки'));},[callApi]);useEffect(load,[load]);return <div className="min-h-screen pb-24"><Header title="Правила"/><main className="space-y-3 p-4">{error?<ErrorText text={error} retry={load}/>:!data?<Loading text="Загрузка правил..."/>:data.documents.length?data.documents.map(doc=><Card key={doc.doc_type}><CardContent className="space-y-3 p-4"><h2 className="text-base font-bold text-foreground">{doc.title}</h2>{doc.content&&<p className="whitespace-pre-wrap text-sm text-muted-foreground">{doc.content}</p>}{doc.file_url&&<Button variant="outline" className="gap-2" onClick={()=>window.open(proxyStorageUrl(doc.file_url??''),'_blank','noopener')}><FileText className="h-4 w-4"/>Открыть файл</Button>}</CardContent></Card>):<Card><CardContent className="py-10 text-center"><ScrollText className="mx-auto mb-2 h-8 w-8 text-muted-foreground"/><p className="text-sm text-muted-foreground">Правила пока не добавлены</p></CardContent></Card>}</main></div>};

interface PyramidData { levels: { id:string;level_number:number;title:string;description:string|null;presentation_url:string|null;is_unlocked:boolean }[] }
export const WebPyramidView=()=>{const{callApi}=useAppApi();const[data,setData]=useState<PyramidData|null>(null);const[error,setError]=useState('');const load=useCallback(()=>{setError('');callApi<PyramidData>('get_pyramid').then(d=>setData({levels:d?.levels??[]})).catch((e:unknown)=>setError(e instanceof Error?e.message:'Ошибка загрузки'));},[callApi]);useEffect(load,[load]);return <div className="min-h-screen pb-24"><Header title="Пирамида КЭМП" subtitle="7 уровней трансформации"/><main className="space-y-3 p-4">{error?<ErrorText text={error} retry={load}/>:!data?<Loading text="Загрузка пирамиды..."/>:data.levels.map(level=><Card key={level.id} className={!level.is_unlocked?'opacity-60':''}><CardContent className="flex items-center gap-3 p-4"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-primary/10 text-sm font-bold text-kamp-primary">{level.level_number}</span><div className="min-w-0 flex-1"><h2 className="text-sm font-semibold text-foreground">{level.title}</h2>{level.description&&<p className="mt-1 text-xs text-muted-foreground">{level.description}</p>}</div>{level.is_unlocked&&level.presentation_url?<Button size="sm" variant="outline" onClick={()=>window.open(proxyStorageUrl(level.presentation_url??''),'_blank','noopener')}>Открыть</Button>:<Lock className="h-4 w-4 text-muted-foreground"/>}</CardContent></Card>)}</main></div>};